language: python

python:
  - 3.6.8
  - 3.7
  - 3.8

services:
  - docker

before_install:
  - apt-get update && apt-get install -y tdsodbc unixodbc-dev
  - apt install unixodbc-bin -y
  - apt-get clean -y

script:
  - docker build -t web-db-manager .
